variables:
  cpus_task: [1, 2] # [1, 4, 9, 16]

leonardo:
  scheduler: slurm

  default_conf:
    account: "TODO"
    partition: "TODO"
    time: "00:10:00"
    modules: 
      - "TODO"
    env:
      - "TODO"

  configs:
    - name: "1_nodes_{cpus_task}_cpu"
      cpus_per_task: "{cpus_task}"
      nodes: 1
      ntasks: 4
      gpus: 4
    - name: "4_nodes_{cpus_task}_cpu"
      cpus_per_task: "{cpus_task}"
      nodes: 4
      ntasks: 16
      gpus: 16
    - name: "9_nodes_{cpus_task}_cpu"
      cpus_per_task: "{cpus_task}"
      nodes: 9
      ntasks: 36
      gpus: 36
    - name: "16_nodes_{cpus_task}_cpu"
      cpus_per_task: "{cpus_task}"
      nodes: 16
      ntasks: 64
      gpus: 64