variables:
  # mtx: '/global/cfs/cdirs/m4646/hns_spgemm_matrices/known_squaring_nnz/matrices_list_mtx.txt'
  mtx:
    - /global/cfs/cdirs/m4646/hns_spgemm_matrices/known_squaring_nnz/Belcastro/mouse_gene/mouse_gene.bmtx
    # - /global/cfs/cdirs/m4646/hns_spgemm_matrices/known_squaring_nnz/GHS_psdef/ldoor/ldoor.mtx
  async_mpi: ['__mpi-async'] #, '']
  args:
   - "--impl get"
   - "--impl main"
   - "--impl main --Acsc"
   # - "--impl main --Acsc --spcomm"

command: "srun -n {np} -G {np} --gpu-bind=single:1 --cpus-per-task=3 --tasks-per-node 4 ./build_hns/run_spgemm --matA {mtx} --matB {mtx} --2D-pgrid {grid} {args}"

jobs:
  - config: "1_nodes__3_cpus-per-task{async_mpi}"
    config_jobs:
      - tag: "HnS-SpGEMM"
        variables:
          np: [4]
          grid: ["1x1", "2x2"]

  # - config: "4_nodes__3_cpus-per-task{async_mpi}"
  #   config_jobs:
  #     - tag: "HnS-SpGEMM"
  #       variables:
  #         np: [16]
  #         grid: ["2x2", "4x4"]

  # - config: "16_nodes__3_cpus-per-task{async_mpi}"
  #   config_jobs:
  #     - tag: "HnS-SpGEMM"
  #       variables:
  #         np: [64]
  #         grid: ["2x2", "4x4", "8x8"]
